<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mayur" ignored="8" name="Default test" tests="1" failures="1" timestamp="08 May 2017 13:42:50 GMT" time="80.188" errors="0">
  <testcase name="testloginWithValidCredentails" time="72.137" classname="test.patient.LoginTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at lib.common.TestBase.failTest(TestBase.java:51)
	at test.patient.LoginTest.testloginWithValidCredentails(LoginTest.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- testloginWithValidCredentails -->
  <testcase name="testLogInFormWithBlankData" time="0.0" classname="test.patient.LoginTest">
    <ignored/>
  </testcase> <!-- testLogInFormWithBlankData -->
  <testcase name="testElementsOfLoginPage" time="0.0" classname="test.patient.LoginTest">
    <ignored/>
  </testcase> <!-- testElementsOfLoginPage -->
  <testcase name="testRegisterLinkFlow" time="0.0" classname="test.patient.LoginTest">
    <ignored/>
  </testcase> <!-- testRegisterLinkFlow -->
  <testcase name="testBrowserbackButtonFlow" time="0.0" classname="test.patient.LoginTest">
    <ignored/>
  </testcase> <!-- testBrowserbackButtonFlow -->
  <testcase name="testSecurityWithInvalidURL" time="0.0" classname="test.patient.LoginTest">
    <ignored/>
  </testcase> <!-- testSecurityWithInvalidURL -->
  <testcase name="testValidationOfLoginForm" time="0.0" classname="test.patient.LoginTest">
    <ignored/>
  </testcase> <!-- testValidationOfLoginForm -->
  <testcase name="testSecurityCheckRedirectToLoginPage" time="0.0" classname="test.patient.LoginTest">
    <ignored/>
  </testcase> <!-- testSecurityCheckRedirectToLoginPage -->
  <testcase name="testNormsAndConditionsLink" time="0.0" classname="test.patient.LoginTest">
    <ignored/>
  </testcase> <!-- testNormsAndConditionsLink -->
</testsuite> <!-- Default test -->
